os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: osx
    - os: windows

language: python
python:
- 3.8

install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: FIXME
  on:
    tags: true
    repo: twiddles/lazyml
    python: 3.8
